services:
  auth:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_NAME:-auth-svc}
    volumes:
      - .:/app
    ports:
      - ${GOLANG_PORT:-8888}:8888
    networks:
      - auth-network

volumes:
  auth-data:

networks:
  auth-network:
    driver: bridge
