###
POST {{base_url}}/api/auth/login HTTP/2.0
Content-Type: application/json
Accept: application/json

{
	"email": "drv.adics@gmail.com",
	"password": "hehe1234",
}

> {%
  const data = response.body.data;
  client.global.set("bearer_token", data.access_token);
  client.global.set("refresh_token", data.refresh_token);
  client.log("tokens stored");
%}
###

###
POST {{base_url}}/api/trip/dispatch/driver/mode HTTP/2.0
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{bearer_token}}

{
	"mode": "offline",
	"current_lat_long": ["-6.14195626401979", "106.81452560937926"],
}
###
